### ISSUE TITLE
Custom font color should change entire header

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#153]
A user pointed out that the custom font color should affect both lines in the header. Currently, only the top one changes.

Expected behavior in the screenshot below: "After 1 round and 1 votes..." should use the same custom color as the line above it.

Also, "1 votes" is ungrammatical and should be changed to "1 vote" (no 's') when vote count = 1. 

![Screenshot 1](https://user-images.githubusercontent.com/10144772/90028133-4dab7780-dc87-11ea-92c4-5c957945dd91.png)

**Comment by proggeramlug** [comment]
Fixed!
