### ISSUE TITLE
Hide overflow of long choices instead of line break on the graph

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#155]
See attached screenshot. Super-long choice names result in completely unreadable graphs.

In the screenshot it looks like maybe 50 characters max fit to a line. Maybe overflow with a "..." after 45ish? 

<img width="640" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/10144772/90185671-0c998d00-dd85-11ea-92e3-f3588b626e9b.png">

**Comment by iambateman** [comment]
CSS has you covered!
