### ISSUE TITLE
Results fixes to match algorithm changes

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#157]
**Background**
The pull request we merged alters eliminations slightly. Before the pull request, there was a "hard elimination" of all choices with 0 votes in Round 1. In multi-winner, however, this created a problem. Example:

- 2 winners are to be chosen from A, B, C
- 5 voters all vote for A first, B second, C third
- A wins in the first round with 100%. B and C are eliminated.
- Because there are no candidates left to receive the surplus votes from A, the algorithm stops after 1 winner.

Thus, the pull request modified the algorithm so the hard elimination occurs in the first round with an elimination--giving time for candidates with 0 votes to receive surplus distributions.

**Issue Description**
This issue is to fix the messaging so it represents this change. See this poll for testing:
https://rankit.skelpo.com/results/P4cL6bavlGkEAKSJJpEJ/1

1. In Round 1, "Phone calls" is already shown as crossed-off. That should not be the case until a choice _with votes_ is eliminated (in this case, Round 2)
2. In Round 1, the Summary reads "So, the choice with the fewest votes, Phone calls, will be eliminated." This is technically true, but the bar that visibly changes is "Written letters" so that should be the one mentioned. In other words, where there are multiple simultaneous eliminations, it's the one with votes to redistribute that should be in the Round Summary.

**Comment by proggeramlug** [comment]
Okay, this doesn't quite make sense.
In the code, for the statement, it says "the choice with least amount of votes will be eliminated". That is the one that received no votes. Should it only be from all choices that have received votes?

So, should we take out all the first round zero vote choices?

To directly speak to the points:
1. So should it be crossed of _later_ with the other one, or should it not show up at all?
2. Similar to #1 in spirit, should "Phone calls" be mentioned at all?

**Comment by ggordn3r** [comment]
Answers to your questions:

1. All choices with 0 votes should be crossed off _later_, together with the first elimination of a choice _with votes_. In this case, that happens in Round 2 (Written letters eliminated).
2. I struggled to find a way to explain this in the Round Summary while preserving our existing message structure. We never did in the last version, but some message is probably best. Try adding this line to the end of the paragraph when more than 1 choice is eliminated in the same round: _All choices with 0 votes will also be eliminated in this round._

You're right, obviously, that a choice with 0 votes has fewer votes than a choice with any. The problem is that the algorithm eliminates all of the choices with 0 votes in a batch in the same round as the first elimination of a choice with votes. So there's no opportunity to explain each of those eliminations separately. Better, I think, just to keep the focus in the Round Summary on the choice with votes, since that's what's highlighted in the graph.

**Comment by proggeramlug** [comment]
Alright, attempting to get this finished finally. Check it out!

**Comment by ggordn3r** [comment]
Round 1 is still mentioning Phone calls instead of Written letters:
https://rankit.skelpo.com/results/P4cL6bavlGkEAKSJJpEJ/1

Also, it looks like I need to reword the message slightly. Instead of  

> All choices with 0 votes will also be eliminated in this round.

Let's say:

> All choices with 0 votes will also be eliminated.

And finally, that message should be in Round 1, not in Round 2 (as it currently is).

**Comment by proggeramlug** [comment]
Okay, I'm somewhat confused but let's just unpack it:
In the first round, no one _is_ eliminated, neither Phone calls nor written letters. There _will_ be an elimination in round 2 and that is what the messaging is saying. "will be eliminated"

So in round 2, this happens but we are eliminating not just written letters but also all the ones with 0 votes. 

The wording here is tricky because "will" and "is" make all the difference here :)

I adjusted the sentence you quoted but not sure how to fix the wording quite correctly.

**Comment by ggordn3r** [comment]
You have this right conceptually, but it's showing up wrong in practice.

Round 1: https://rankit.skelpo.com/results/P4cL6bavlGkEAKSJJpEJ/1
- Message says the choice with the fewest votes "will be eliminated" (correct)
- No mention of choices with 0 votes (incorrect)

Round 2: https://rankit.skelpo.com/results/P4cL6bavlGkEAKSJJpEJ/2
- Message says "All choices with 0 votes will also be eliminated." (correct message, 1 round late)

Expected behavior is for these messages to appear together in the first round. The choices with no votes will be eliminated at the same time as the first choice _with_ votes is eliminated, so their "will be" messages should appear together in the same round.

**Comment by proggeramlug** [comment]
Okay, fixed it to appear in the same round now.

**Comment by ggordn3r** [comment]
Confirmed, correct round. Now we just need to change "Phone calls" to "Written letters" in Round 1:
https://rankit.skelpo.com/results/P4cL6bavlGkEAKSJJpEJ/1

Notice that in Round 2 it's "Written letters" that is visibly eliminated. In situations where more than one choice is eliminated (the first elimination, where choices with 0 votes are also eliminated), the one with votes is the one to mention in the text.

**Comment by proggeramlug** [comment]
Okay, I had to change our "getLoosers()" function slightly to take out all the objections without votes - let's test this really well (but we can test it in live I think).

**Comment by ggordn3r** [comment]
Beautiful. Closing!
