### ISSUE TITLE
Bar of winners exceeds allowable length

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#159]
Stephen already fixed this, so something reintroduced this bug. A bar over the threshold any amount should be set to a fixed maximum length (103 if I remember correctly--ask Stephen if it's not obvious in the code).

Currently, the bar extends past the previous maximum so that it obscures the Round Summary. See, for example, the bar for Arizona in this round:
https://rankit.skelpo.com/results/eaub53HYQM70lX5J8az7/6

![rankIt](https://user-images.githubusercontent.com/10144772/91115541-70ab3380-e658-11ea-9d0e-20e698b1591e.PNG)

**Comment by proggeramlug** [comment]
Fixed - not quite but close (110 is what I set it to so that is looks good)

**Comment by ggordn3r** [comment]
Still a bit too long. The bar shouldn't go past the % mark in the threshold label or it causes problems on mobile. Try 103.

**Comment by proggeramlug** [comment]
Changed it to 103.
