### ISSUE TITLE
Preview doesn't display custom colors

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#160]
The preview feature seems to be broken right now. See, for example, this poll:
https://rankit.skelpo.com/results/VNQWkCqW8JIQuQ39NHFR/summary

I don't see any of the custom branding I chose.

Also, testers pointed out that the preview doesn't have buttons, so it can't show custom button colors. Can you add example buttons?

**Comment by proggeramlug** [comment]
Problem is that you forgot to include "#". Since this is probably more common than not I have included a check that will automatically add the symbol in code if needed.

**Comment by ggordn3r** [comment]
Thanks, I see the bar and font colors now. I see a "back to home page" button but it's not the class of button that shows custom colors. See description--to allow super users to review all their custom branding choices, we also need two buttons on this page (even if they don't do anything) that show button color 1 and button color 2.

Let's do this:
- if `is_published = false`
- Show a button that says "Button Color 1 Preview" with the button 1 class
- Show a button that says "Button Color 2 Preview" with the button 2 class

**Comment by proggeramlug** [comment]
This is done now - note however that the poll referenced above is already published, so the condition does not apply here.

**Comment by ggordn3r** [comment]
Cool. I asked the client to retest.

**Comment by ggordn3r** [comment]
I created a new poll and added custom colors throughout but don't see the new preview buttons:
https://rankit.skelpo.com/results/Ebu7i5FHENcT4YJ2m4Pg/summary

![image](https://user-images.githubusercontent.com/10144772/91664618-6f499300-eabe-11ea-84d2-b61b63181169.png)

**Comment by proggeramlug** [comment]
Well, this poll is already published ...

**Comment by ggordn3r** [comment]
No, it's not:

![image](https://user-images.githubusercontent.com/10144772/91726098-b478ce00-eb6d-11ea-8b83-a0a085d59e5d.png)

**Comment by proggeramlug** [comment]
Ah, found the problem and fixed it!
