### ISSUE TITLE
At tablet size, button wraps out of sight

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#161]
See screenshot. Just a small responsive design issue:

![image](https://user-images.githubusercontent.com/10144772/91116337-1f9c3f00-e65a-11ea-9733-2e204fd06005.png)

You can also try stretching this screen back and forth:
https://rankit.skelpo.com/results/eaub53HYQM70lX5J8az7/1

**Comment by proggeramlug** [comment]
Fixed. It looks a little funny when you play with the screens on desktop because the button style changes at some point to the mobile (phone) view but I think this works well.
