### ISSUE TITLE
With 1 winner, match grammatical case with "wins" instead of "win"

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#162]
See screenshot. "a win" is not grammatical. Should be "wins" with an "s" when only 1 winner is declared.

![image](https://user-images.githubusercontent.com/10144772/91200382-17c9b280-e6cd-11ea-9d64-e25815b2b26d.png)

Poll URL: https://rankit.skelpo.com/results/ieXixApNbCyecLYdHP3Z/summary

**Comment by proggeramlug** [comment]
Good find! Fixed!
