### ISSUE TITLE
Winners object not populating on live site (rankit.vote) for all results

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#163]
I know it's a pain to have to go into the live side and fix this, but it's a global issue that's affecting all results. See, for example:
https://rankit.vote/results/O5z48DDWEe50fsiKXIyw/summary
https://rankit.vote/results/z8mDElhcoY4JagtFuVBt/summary

> After 5 rounds and 511 votes, [object Object] wins.

Because of that, I don't think it can wait until the big push, even if that's just a couple of days away. :/

**Comment by proggeramlug** [comment]
I don't see how we can do this without "a big push". The algorithm changed the way the results look like and to adjust it, even if we are not doing all the current changes would be a decently massive update. I so much rather get it fixed.

There is no reason not to push the current update even _as is_ compared to what changes we will need anyways for this fix.
