### ISSUE TITLE
Why does this poll have a surplus redistribution round if no votes are being redistributed?

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#165]
Take a look at rounds 2 and 3 of this poll with "Show Vote Count" toggled on:
https://rankit.skelpo.com/results/P4cL6bavlGkEAKSJJpEJ/2

- In round 2, "Video chats" wins with 5 votes and the round summary says their votes will be reallocated.
- In round 3, the bar visibly shortens, but the vote count remains 5 and no other vote counts increase.

Is this just some funny business with rounding behind the scenes?

**Comment by proggeramlug** [comment]
I believe so. If you check out the percentages you see the decrease from 38% to 33%. In addition, we are showing the previous-round-winners with full threshold values after they won. "Video chats" won in round 2 and is then simply shown as "reaching the threshold" in the following rounds.

I'm not sure what a fix would look like here.

**Comment by ggordn3r** [comment]
I think we'll just have to accept this as a known issue. We can't really help what the algorithm is doing behind the scenes and it would be pretty tricky to ignore surplus redistribution only when the amount is insignificant.
