### ISSUE TITLE
Internal server error on 1 round poll

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#167]
I created a new poll and voted in it. I clicked "view results" and then "see results by round". Got an internal server error:
https://rankit.vote/results/FB7Fq65KpCaQiS4zMwyW/summary

![image](https://user-images.githubusercontent.com/10144772/92249151-a392ca00-ee97-11ea-977d-4cd5551df5e0.png)

Update: seems like it may be universal. Client also reporting:
https://rankit.vote/results/41vxTFg2QyaK9mlzX2Wx/summary

**Comment by proggeramlug** [comment]
Fixed!
