### ISSUE TITLE
"Finish" button after results leads to blank page

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#168]
Client reports the results for this poll work fine until you click "Finish" on the last page:
https://rankit.skelpo.com/results/foMd8h00C8ecvb7AbjOf/5 (notice this was discovered on staging)

Then it leads to a blank page instead of the expected CTA page. Looks like the URL does something odd--I saw /summary once, then /5 the next time I clicked.

![image](https://user-images.githubusercontent.com/10144772/92249883-beb20980-ee98-11ea-93ed-7f7e309b1c08.png)

 If I switch over to the live version, I get "Internal Server Error" for all results:

![image](https://user-images.githubusercontent.com/10144772/92250069-ff118780-ee98-11ea-8166-4171c89d54e2.png)

but not for the "vote" page:
https://rankit.vote/vote/foMd8h00C8ecvb7AbjOf

**Comment by proggeramlug** [comment]
Outdated stage version - fixed when I deployed the current one. :)
