### ISSUE TITLE
Using the back button causes "My Polls" link to fail

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#169]
I've noticed this in a few contexts. Sometimes I just want to click "back" (e.g. from the results preview back to the poll management page, or from this round of results to the last). After I do this a couple of times, clicking the "My Polls" link does nothing.

- For example, I clicked forward through the results of this poll from the summary:
https://rankit.skelpo.com/results/foMd8h00C8ecvb7AbjOf/summary
- Then after making it to round 5, clicked "back" all the way to round 1
- Then clicked "My Polls". Nothing happens.
- Then I clicked "My Account" and it worked. From there, I can click "My Polls" no problem. It works the same way if I click the "Home" button.

**Comment by proggeramlug** [comment]
Probably the same error we had on staging in the other ticket, it works for me now!
