### ISSUE TITLE
"All choices with 0 votes" message errors

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#170]
The message should appear in this round but is missing:
https://rankit.skelpo.com/results/de1eyhhPBSLzxSKQ3JHo/1

When there is no choice with 0 votes, the message shows in every elimination round (see rounds 2,3,4) but should not appear at all:
https://rankit.skelpo.com/results/foMd8h00C8ecvb7AbjOf/2

For reference, the original issue was #157

**Comment by proggeramlug** [comment]
Fixed it
