### ISSUE TITLE
Votes don't add up between graph and summary

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#172]
User-reported. In this poll:
https://rankit.vote/results/foMd8h00C8ecvb7AbjOf/summary

The summary says "34 votes" but the totals only add up to 30-31 through the rounds. Rounding error would only explain a difference of 1, I think, so something else is off. The percentages in the last round also add up to just 85.9.

**Comment by proggeramlug** [comment]
Problem found and fixed!
