### ISSUE TITLE
Voting doom loop

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#174]
User reported:
https://rankit.vote/vote/lDfQ608ZYDdUQ9gZcYHB

When you vote in that poll (rank --> captcha --> submit) it reloads the vote page. Expected behavior is to load the results.

**Update**: confirmed in a second poll (https://rankit.vote/vote/0UWhQWceeNbDD3Jp8vi1)

**Comment by proggeramlug** [comment]
Found the problem and fixed it.

**Comment by ggordn3r** [comment]
Just tested 4 ways on the first link (while logged in, hard refresh, while logged out, and incognito) and am still getting the same problem.

**Comment by proggeramlug** [comment]
I spoke too soon, it wasn't on the server yet (now it is)
