### ISSUE TITLE
RCVIS results slider does not slide

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#180]
Try dragging the results slider on this poll from Round 4 to Round 1:
https://www.rcvis.com/v/rankit-data-1780085

I can't tell if this is our bug or theirs.

![image](https://user-images.githubusercontent.com/10144772/97111807-2de8f480-16b7-11eb-9128-990b6a254769.png)
 
_Reported by Louis Eisenberg_

**Comment by proggeramlug** [comment]
tentatively their bug as it is on their site, but we might be able to serve it better to them. we should play it to them first though
