### ISSUE TITLE
Submit button lagging, submitting multiple votes

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#185]
After Captcha, a click on "Submit My Vote" does not appear to change anything on screen. The Submit button remains active and can be clicked multiple times to submit multiple votes. The "thank you" page does not load.

Expected behavior is for the Submit button to be disabled after clicking once and the thank you page to load.

I think we addressed this once before, but 3 users have reported it again this morning. I just reproduced it on:
https://rankit.vote/vote/FXUgedU7qyzsEdlnVUoC

**Comment by proggeramlug** [comment]
this should be fixed now. I tested in a private window in firefox

**Comment by czawora** [comment]
Is the version fixing this merged into master? I tried deploying a new version, just to change some footer text, and this bug re-appeared. It also looks like the code of the last deployment (vote component submitVote [function](https://github.com/fairvotereform/RankIt/blob/d1aad48fe4c06e32e7e5530d7e7dd800e265dd57/src/app/vote/pages/vote/vote.component.ts#L178)) on Google app engine doesn't match the master branch either.

**Comment by czawora** [comment]
Fixed by Ralph merging local commits to github
